version: "3.8"

services:
  app:
    build: .
    ports:
      - "8081:8081"  # Metro bundler (React Native)
      - "7000:7000"  # Python RFID Server
      - "7001:7001"  # Camera Capture Server
      - "8082:8082"  # External port exposure
      - "5001:5001"  # CORS Proxy for 8082
    volumes:
      - .:/project-root
    stdin_open: true
    tty: true
